### ISSUE TITLE
Script runs successfully but corners stay unchanged

### ISSUE THREAD

**Issue by sebreens** [rich-ayr/win11-toggle-rounded-corners#1]
Heya!

I am excited to see that an easy solution for this is developed but unfortunately it doesn't seem to work on my machine.

I am on Version 21H2(OS Build 22000.856) and this is what I get when I run the executable from my powershell:
`PS C:\Users\helvi\Downloads> .\win11-toggle-rounded-corners.v1.0.exe                                                    Found dwm.exe process [window handle: 0x20042, pid: 1508].                                                              Opened process handle 0x110 to dwm.exe.                                                                                 Locating CDesktopManager *g_pdmInstance:                                                                                  00007FFD866A1CD0  push rbx                                                                                              00007FFD866A1CD2  sub rsp, 0x30                                                                                         00007FFD866A1CD6  call 0x00007FFD866A1EF4                                                                               00007FFD866A1EF4  mov [rsp+0x08], rbx                                                                                   00007FFD866A1EF9  mov [rsp+0x10], rdx                                                                                   00007FFD866A1EFE  push rdi                                                                                              00007FFD866A1EFF  sub rsp, 0x30                                                                                         00007FFD866A1F03  mov rdi, rcx                                                                                          00007FFD866A1F06  lea rcx, [0x00007FFD867964A8]                                                                         00007FFD866A1F0D  mov [rsp+0x48], rcx                                                                                   00007FFD866A1F12  call [0x00007FFD86764618]                                                                             00007FFD866A1F19  nop [rax+rax*1], eax                                                                                  00007FFD866A1F1E  nop                                                                                                   00007FFD866A1F1F  mov rcx, [0x00007FFD86792CC8]                                                                         00007FFD866A1F26  mov rax, [rcx]                                                                                        00007FFD866A1F29  mov r10, -0x1E5AE167EF230590                                                                          00007FFD866A1F33  mov edx, 0x348                                                                                        00007FFD866A1F38  mov rax, [rax+0x10]                                                                                   00007FFD866A1F3C  call [0x00007FFD86764B60]                                                                             00007FFD866A1F42  mov [rsp+0x50], rax                                                                                   00007FFD866A1F47  test rax, rax                                                                                         00007FFD866A1F4A  jz 0x00007FFD866A1F94                                                                                 00007FFD866A1F4C  mov rcx, rax                                                                                          00007FFD866A1F4F  call 0x00007FFD866A1CF4                                                                               00007FFD866A1F54  mov rbx, rax                                                                                          00007FFD866A1F57  test rbx, rbx                                                                                         00007FFD866A1F5A  jz 0x00007FFD866DDC7C                                                                                 00007FFD866A1F60  mov rdx, rdi                                                                                          00007FFD866A1F63  mov rcx, rbx                                                                                          00007FFD866A1F66  call 0x00007FFD866A26E0                                                                               00007FFD866A1F6B  mov edi, eax                                                                                          00007FFD866A1F6D  test eax, eax                                                                                         00007FFD866A1F6F  js 0x00007FFD866DDCAE                                                                                 00007FFD866A1F75  mov [0x00007FFD86796528], rbx                                                                       Found g_pdmInstance at RVA 0x146528.                                                                                    Found udwm.dll mapped at 0x7ffd86650000.                                                                                  g_pdmInstance = (CDesktopManager *)0x16a8e27c880;                                                                                                                                                                                             Your rounded corners were 'enabled', they are now being disabled...                                                     Success!    `

Any help would be appreciated.

**Comment by rich-ayr** [comment]
It applies when switching to a different window. If switching windows doesn't fix please attach your `C:\Windows\system32\udwm.dll` here.
