### ISSUE TITLE
Win 11 start menu, Alt-Tab preview, Windows-Tab preview corners unchanged

### ISSUE THREAD

**Issue by bpcw** [rich-ayr/win11-toggle-rounded-corners#11]
Hi,
not exactly an issue, more of a question.
The tool as such works well in removing the rounded corners for anything controlled by dwm (as I understand, it does some in-memory patching of dwm.exe).
However, the Win 11 start menu, the Desktop view (Windows-Tab) and Task Switcher (Alt-Tab) still show round corners.
Is there any investigation into adjusting this too?
Thanks

**Comment by rich-ayr** [comment]
You can check out @valinet's sws or ExplorerPatcher to bring back Windows 10 Alt+Tab with sharp corners.
There's also StartAllBack and Start11 on the commercial side.

**Comment by bpcw** [comment]
> You can check out @valinet's sws or ExplorerPatcher to bring back Windows 10 Alt+Tab with sharp corners. There's also StartAllBack and Start11 on the commercial side.

Ok. Thanks. 
I went back to Win 10 for now anyway, for multiple reasons. Win 11 is not my cup of tea. Maybe Win 12 (or whatever it will be called) is going to be better for me again.
