### ISSUE TITLE
Doesn't change anything

### ISSUE THREAD

**Issue by radio303** [rich-ayr/win11-toggle-rounded-corners#13]
Hello. I've tried using this but nothing changes. I ran the file with administrative privileges. Possibly some update prevents it from working.

**Comment by rich-ayr** [comment]
Still works fine on my machine running latest Windows 11 Insider Build.

![screenshot](https://i.imgur.com/kL0c0mC.png)

The effect only applies after Alt+Tab.

**Comment by rich-ayr** [comment]
Closed due to inactivity
