### ISSUE TITLE
Broke windows

### ISSUE THREAD

**Issue by NoahBakayou** [rich-ayr/win11-toggle-rounded-corners#14]
I downloaded the precompiled binaries and this has caused my computer to flash repeatedly even after restarting. I can't even open explorer to delete the file, only thing I can open is task manager. Please help me fix this horrible issue, I don't want to lose any data.

**Comment by rich-ayr** [comment]
The changes by the program are only temporary and won't stay in effect after a restart of your PC.

**Comment by NoahBakayou** [comment]
Not true my computer is still broken.

**Comment by rich-ayr** [comment]
I don't see how the program could cause this. Please provide more information than "my pc flashing", "not working", etc. Maybe include a screenshot.

**Comment by NoahBakayou** [comment]
I'm sorry I can't even open anything on my pc to take a screen shot. I have to take it into a computer repair store now, I hope they can recover my data :(

**Comment by rich-ayr** [comment]
You could take a picture with your phone.

I recommend retracing your steps, the program doesn't change any system setting and doesn't stay active after reboot so it has to be something else you did around the same time/day.

**Comment by NoahBakayou** [comment]
That's interesting but it literally happened right when I opened the installed file, I think it corrupted something in windows. When I have time, I'll try to upload a picture. Thank you for your help
