### ISSUE TITLE
Does this program hook into running resources

### ISSUE THREAD

**Issue by bbmaster123** [rich-ayr/win11-toggle-rounded-corners#2]
I believe it hooks, changes the Boolean value, and does that all in memory, correct? This way it does not actually save changes to udwm.dll?

**Comment by rich-ayr** [comment]
This method does not require hooks, here's what it does step by step:
- Maps `udwm.dll` into local address space using `LoadLibraryExA(..., DONT_RESOLVE_DLL_REFERENCES)`
- Disassembles `DwmClientStartup` function using Zydis to find the RVA (relative virtual address) of `g_pdmInstance`, which is assigned inside `CDesktopManager::Create`
- Opens a handle to `dwm.exe`, finds `udwm.dll` in the remote process and translates the `g_pdmInstance` to a VA.
- Now it simply dereferences the `g_pdmInstance` pointer and writes `true`/`false` to the "`enable_rounded_corners`" `bool` (The structure is undocumented and there are no symbols for it, so the variable name here is just a wild guess).

Other methods instead rely on hooking functions or replacing system files which invalidates code/file integrity of the modified system files/functions. This however does not cause any such violations and is purely based on modifying writable data inside the heap.

**Comment by bbmaster123** [comment]
I believe I understand, thanks for the detailed explanation

**Comment by xpirad** [comment]
Sorry i'm a bit late to the party, but i'm still trying to figure out the difference between these implementations, namely:
(1) https://github.com/valinet/ExplorerPatcher
(2) https://github.com/valinet/Win11DisableRoundedCorners
and this repo (3) https://github.com/oberrich/win11-toggle-rounded-corners/

The thing that l want to know is if there's any difference in the way of removing the rounded corner 

And also, a big thank you to you all, you guys rock!

======
So as per my understanding:
(1)&(2) from above needs to modify system file
whereas (3) doesn't
am I seeing this correctly? Thanks!

**Comment by xpirad** [comment]
Also, does this tool needs to be updated/re-compiled when there's a new windows update?

**Comment by rich-ayr** [comment]
> Sorry i'm a bit late to the party, but i'm still trying to figure out the difference between these implementations, namely: (1) https://github.com/valinet/ExplorerPatcher (2) https://github.com/valinet/Win11DisableRoundedCorners and this repo (3) https://github.com/oberrich/win11-toggle-rounded-corners/
> 
> The thing that l want to know is if there's any difference in the way of removing the rounded corner
> 
> And also, a big thank you to you all, you guys rock!
> 
> ====== So as per my understanding: (1)&(2) from above needs to modify system file whereas (3) doesn't am I seeing this correctly? Thanks!

(1) Explorer patcher is using a service to patch `uDWM.dll.text` section.
(2) Replaces system files, this is a terrible approach and has a lot of issues.
(3) Offers two modes:
- `(default)`: Patches two floats inside the `uDWM.dll.rdata` section.
- `--no-patching`: This forces DWM to use the WARP adapter, which isn't perfect but works by changing a value inside DWM's heap; this won't cause any integrity violations.

> Also, does this tool needs to be updated/re-compiled when there's a new windows update?

For `(default)` method: Only if MSFT decides to change the values (4.0, 8.0) of the rounding floats or significantly changes the way rounded corners work.
For `--no-patching`: This should also be quite robust as well, it's using the [Zydis disassembler](https://github.com/zyantific/zydis) to dynamically find the global `CDesktopManager` instance.

**Comment by xpirad** [comment]
Cool! Now I see what's happening!
Thanks for the explanation and your work, oberrich!
