### ISSUE TITLE
Grey borders appear when windows are in split screen view

### ISSUE THREAD

**Issue by Auradyme** [rich-ayr/win11-toggle-rounded-corners#20]
https://imgur.com/m2GAWGg

**Comment by rich-ayr** [comment]
Never noticed, I guess we have an indicator for when your window is "pinned" now. ¯\_(ツ)_/¯

This way of disabling the corners offers quite little control, there is API support to change corner style/preference or whatever they called it now, maybe I could use this instead if available.

There's most likely a simple way to fix this but not sure if it's worth it to even look into it before trying the new API.
If anyone knows of a simple fix, I'm happy to add it.
