### ISSUE TITLE
Doesn't work with 10.0.22631 Build 22631

### ISSUE THREAD

**Issue by bebuch** [rich-ayr/win11-toggle-rounded-corners#21]
I used this patch for some time, but now I see round corners again. Re-Applying dones't work eighter. The Output tells me a success, but after a restart I still see round corners.

My Windows version is 10.0.22631 Build 22631.

**Comment by rich-ayr** [comment]
Still works for me, I'm also running build 22631.
You shouldn't have to restart for the program to work.
Maybe it's an issue with your Defender/Anti-Virus software?

![image](https://github.com/oberrich/win11-toggle-rounded-corners/assets/6305520/82e5d5f7-d5f2-45fa-a444-9c2247e959dd)

**Comment by bebuch** [comment]
Thanks for the feedback! I use Sophos as virus scanner, but unfortunately I don't have access to the settings.

If it still works for you, then something on my computer must be preventing the patch from working.
